#!/usr/bin/env python3
"""
Extract Matter session keys from chip-tool logs.

Parses chip-tool log output containing session key derivation messages
and writes a keylog file consumable by the Matter Wireshark dissector.

Usage:
    python3 matter_keylog_extract.py < chip-tool.log > matter_keys.log
    python3 matter_keylog_extract.py chip-tool.log -o matter_keys.log
    python3 matter_keylog_extract.py chip-tool.log  # prints to stdout
"""

import re
import sys
import argparse


def extract_hex_bytes(lines, start_idx):
    """Extract hex bytes from consecutive log lines starting at start_idx."""
    hex_bytes = []
    for i in range(start_idx, min(start_idx + 10, len(lines))):
        line = lines[i]
        values = re.findall(r'0x([0-9a-fA-F]{2})', line)
        if not values:
            break
        hex_bytes.extend(values)
        if not line.rstrip().endswith(','):
            break
    return ''.join(hex_bytes)


def extract_session_id(lines, key_line_idx):
    """Search backwards from key derivation for session ID assignments."""
    local_id = None
    peer_id = None
    search_start = max(0, key_line_idx - 50)
    for i in range(key_line_idx, search_start, -1):
        line = lines[i]
        m = re.search(
            r'Assigned local session key ID (\d+)', line
        )
        if m and local_id is None:
            local_id = int(m.group(1))
        m = re.search(r'Peer assigned session ID (\d+)', line)
        if m and peer_id is None:
            peer_id = int(m.group(1))
        if local_id is not None and peer_id is not None:
            break
    return local_id, peer_id


def extract_keys(log_text):
    """Extract all session key sets from chip-tool log text."""
    lines = log_text.splitlines()
    results = []

    for idx, line in enumerate(lines):
        if 'Session Keys Derived' not in line:
            continue

        role_match = re.search(r'Role:\s*(\w+)', line)
        role = role_match.group(1) if role_match else 'Unknown'

        i2r_key = ''
        r2i_key = ''
        att_challenge = ''

        for j in range(idx + 1, min(idx + 20, len(lines))):
            if 'I2R Key' in lines[j]:
                i2r_key = extract_hex_bytes(lines, j + 1)
            elif 'R2I Key' in lines[j]:
                r2i_key = extract_hex_bytes(lines, j + 1)
            elif 'Attestation Challenge' in lines[j]:
                att_challenge = extract_hex_bytes(lines, j + 1)
            elif 'Session Keys Derived' in lines[j] and j != idx:
                break

        if len(i2r_key) != 32 or len(r2i_key) != 32:
            continue

        local_id, peer_id = extract_session_id(lines, idx)

        results.append({
            'role': role,
            'i2r': i2r_key,
            'r2i': r2i_key,
            'attestation_challenge': att_challenge,
            'local_session_id': local_id,
            'peer_session_id': peer_id,
        })

    return results


def format_keylog(key_sets):
    """Format extracted keys as keylog file content."""
    lines = [
        "# Matter Session Key Log",
        "# Generated by matter_keylog_extract.py",
        "#",
        "# Format: SESSION_ID  I2R_KEY  R2I_KEY",
        "# SESSION_ID: * = try all sessions, or specific decimal ID",
        "# Keys: 32-char hex (128-bit AES)",
        "#",
    ]

    for ks in key_sets:
        comment = f"# Role: {ks['role']}"
        if ks['local_session_id'] is not None:
            comment += f", Local ID: {ks['local_session_id']}"
        if ks['peer_session_id'] is not None:
            comment += f", Peer ID: {ks['peer_session_id']}"
        if ks['attestation_challenge']:
            comment += f"\n# Attestation Challenge: {ks['attestation_challenge']}"
        lines.append(comment)
        lines.append(f"*  {ks['i2r']}  {ks['r2i']}")
        lines.append("")

    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(
        description='Extract Matter session keys from chip-tool logs'
    )
    parser.add_argument(
        'logfile', nargs='?', default='-',
        help='Chip-tool log file (default: stdin)'
    )
    parser.add_argument(
        '-o', '--output', default='-',
        help='Output keylog file (default: stdout)'
    )
    args = parser.parse_args()

    if args.logfile == '-':
        log_text = sys.stdin.read()
    else:
        with open(args.logfile) as f:
            log_text = f.read()

    key_sets = extract_keys(log_text)

    if not key_sets:
        print("No session keys found in log.", file=sys.stderr)
        print(
            "Ensure chip-tool was built with CHIP_DETAIL_LOGGING=1",
            file=sys.stderr,
        )
        return 1

    print(
        f"Found {len(key_sets)} session key set(s).",
        file=sys.stderr,
    )

    output = format_keylog(key_sets)

    if args.output == '-':
        sys.stdout.write(output)
    else:
        with open(args.output, 'w') as f:
            f.write(output)
        print(f"Written to {args.output}", file=sys.stderr)

    return 0


if __name__ == '__main__':
    sys.exit(main())
